import Head from "next/head";

const Header = () => {
    return (
        <Head>
            <title>Muslim Roadmap</title>
            <meta name="description" content="Generated by Muslim Roadmap team" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default Header;
